# Generated by Django 5.2 on 2025-05-30 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_alter_historicalpond_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpond',
            name='assessment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Нормативна оцінка'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координати'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='date_approval',
            field=models.DateField(blank=True, null=True, verbose_name='Дата погодження'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Відсоток'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='pass_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Площа (га)'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='pass_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Глибина, м'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='pass_developer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Розробник'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='pass_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва папорту'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='pass_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='№ реєстру'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='pass_volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Обєм при НПР'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='rent_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець оренди'),
        ),
        migrations.AlterField(
            model_name='historicalpond',
            name='rent_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок оренди'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='assessment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Нормативна оцінка'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координати'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='date_approval',
            field=models.DateField(blank=True, null=True, verbose_name='Дата погодження'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Відсоток'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pass_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Площа (га)'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pass_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Глибина, м'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pass_developer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Розробник'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pass_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва папорту'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pass_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='№ реєстру'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pass_volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Обєм при НПР'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='rent_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець оренди'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='rent_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок оренди'),
        ),
    ]
