# Generated by Django 5.2 on 2025-06-12 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallandplot',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координати'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='date_approval',
            field=models.DateField(blank=True, null=True, verbose_name='Дата погодження'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='gidr_constr',
            field=models.CharField(choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Гідроспоруда'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='gidr_coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координати гідроспоруди'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='gidr_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ акта гідроспоруди'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='pass_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Площа (га)'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='pass_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Глибина, м'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='pass_developer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Розробник'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='pass_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва папорту'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='pass_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ реєстру'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='pass_volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Обєм при НПР'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'вланість'), ('5', 'аукціон')], default=2, max_length=255, verbose_name='Статус права'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landplot',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координати'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='date_approval',
            field=models.DateField(blank=True, null=True, verbose_name='Дата погодження'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='gidr_constr',
            field=models.CharField(choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Гідроспоруда'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='gidr_coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координати гідроспоруди'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='gidr_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ акта гідроспоруди'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='pass_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Площа (га)'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='pass_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Глибина, м'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='pass_developer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Розробник'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='pass_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва папорту'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='pass_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№ реєстру'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='pass_volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Обєм при НПР'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'вланість'), ('5', 'аукціон')], default='2', max_length=255, verbose_name='Статус права'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='assessment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Нормативна оцінка'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='cadastr_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Кадастровий номер'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Відсоток'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='land',
            field=models.CharField(blank=True, choices=[('1', '001.01 Рілля'), ('2', '001.02 Перелоги'), ('3', '001.03 Парники, оранжереї, теплиці'), ('4', '002.01 Сіножаті'), ('5', '002.02 Пасовища'), ('6', '002.03 Багаторічні насадження'), ('7', "003.01 Кам'янисті місця"), ('8', '003.02 Піски'), ('9', '003.03 Болота'), ('10', '003.04 Солончаки'), ('11', '003.05 Яри'), ('12', '003.06 Степи'), ('13', '004.00 Чагарникова рослинність природного походження'), ('14', '005.01 Земельні лісові ділянки, вкриті лісовою рослинністю'), ('15', '005.02 Земельні лісові ділянки, не вкриті лісовою рослинністю'), ('16', '005.03 З усіх лісів лісові насадження лінійного типу'), ('17', '005.04 Інші лісовкриті площі'), ('18', '005.05 Самозалісені землі'), ('19', '006.01 Природні водотоки (річки та струмки)'), ('20', '006.02 Штучні водотоки (канали, колектори, канави)'), ('21', '006.03 Озера, прибережні замкнуті водойми, лимани'), ('22', '006.04 Ставки'), ('23', '006.05 Штучні водосховища'), ('24', '007.01 Малоповерхова забудова'), ('25', '007.02 Багатоповерхова забудова'), ('26', '008.01 Землі під громадськими спорудами, які мають історико-архітектурну цінність, об’єктами культурної спадщини, адміністративними будівлями'), ('27', '008.02 Вулиці та бульвари (включаючи тротуари), набережні, площі'), ('28', "008.03 Землі під соціально-культурними об'єктами"), ('29', '009.01 Землі під залізницями'), ('30', '009.02 Землі під дорогами, зокрема підґрунтовими'), ('31', '009.03 Землі під будівлями та спорудами транспорту'), ('32', '010.00 Землі, які використовуються для технічної інфраструктури'), ('33', '011.01 Землі під будівлями та спорудами промислових підприємств'), ('34', "011.02 Землі під відкритими розробками, шахтами, кар'єрами, торфорозробками та відповідними спорудами"), ('35', '011.03 Землі, які забруднені промисловими та іншими відходами, включаючи відвали та терикони, а також радіоактивно забруднені'), ('36', '012.00 Землі, зайняті поточним будівництвом та відведені під будівництво (будівництво на яких не розпочато)'), ('37', '013.00 Землі під сільськогосподарськими та іншими господарськими будівлями і дворами'), ('38', '014.00 Землі, які використовуються для відпочинку та оздоровлення'), ('39', "015.01 Землі під військовими базами, об'єктами, фортецями, фортами укріплення"), ('40', "015.02 Землі під кладовищами, крематоріями, меморіальними комплексами та пам'ятниками, скотомогильниками"), ('41', '015.03 Землі, які перебувають у стадії меліоративного освоєння та відновлення родючості ґрунтів')], verbose_name='Угіддя'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='registered',
            field=models.CharField(choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Договір зареєстрований'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='assessment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Нормативна оцінка'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='cadastr_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Кадастровий номер'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Відсоток'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='land',
            field=models.CharField(blank=True, choices=[('1', '001.01 Рілля'), ('2', '001.02 Перелоги'), ('3', '001.03 Парники, оранжереї, теплиці'), ('4', '002.01 Сіножаті'), ('5', '002.02 Пасовища'), ('6', '002.03 Багаторічні насадження'), ('7', "003.01 Кам'янисті місця"), ('8', '003.02 Піски'), ('9', '003.03 Болота'), ('10', '003.04 Солончаки'), ('11', '003.05 Яри'), ('12', '003.06 Степи'), ('13', '004.00 Чагарникова рослинність природного походження'), ('14', '005.01 Земельні лісові ділянки, вкриті лісовою рослинністю'), ('15', '005.02 Земельні лісові ділянки, не вкриті лісовою рослинністю'), ('16', '005.03 З усіх лісів лісові насадження лінійного типу'), ('17', '005.04 Інші лісовкриті площі'), ('18', '005.05 Самозалісені землі'), ('19', '006.01 Природні водотоки (річки та струмки)'), ('20', '006.02 Штучні водотоки (канали, колектори, канави)'), ('21', '006.03 Озера, прибережні замкнуті водойми, лимани'), ('22', '006.04 Ставки'), ('23', '006.05 Штучні водосховища'), ('24', '007.01 Малоповерхова забудова'), ('25', '007.02 Багатоповерхова забудова'), ('26', '008.01 Землі під громадськими спорудами, які мають історико-архітектурну цінність, об’єктами культурної спадщини, адміністративними будівлями'), ('27', '008.02 Вулиці та бульвари (включаючи тротуари), набережні, площі'), ('28', "008.03 Землі під соціально-культурними об'єктами"), ('29', '009.01 Землі під залізницями'), ('30', '009.02 Землі під дорогами, зокрема підґрунтовими'), ('31', '009.03 Землі під будівлями та спорудами транспорту'), ('32', '010.00 Землі, які використовуються для технічної інфраструктури'), ('33', '011.01 Землі під будівлями та спорудами промислових підприємств'), ('34', "011.02 Землі під відкритими розробками, шахтами, кар'єрами, торфорозробками та відповідними спорудами"), ('35', '011.03 Землі, які забруднені промисловими та іншими відходами, включаючи відвали та терикони, а також радіоактивно забруднені'), ('36', '012.00 Землі, зайняті поточним будівництвом та відведені під будівництво (будівництво на яких не розпочато)'), ('37', '013.00 Землі під сільськогосподарськими та іншими господарськими будівлями і дворами'), ('38', '014.00 Землі, які використовуються для відпочинку та оздоровлення'), ('39', "015.01 Землі під військовими базами, об'єктами, фортецями, фортами укріплення"), ('40', "015.02 Землі під кладовищами, крематоріями, меморіальними комплексами та пам'ятниками, скотомогильниками"), ('41', '015.03 Землі, які перебувають у стадії меліоративного освоєння та відновлення родючості ґрунтів')], verbose_name='Угіддя'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='registered',
            field=models.CharField(choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Договір зареєстрований'),
        ),
    ]
