# Generated by Django 5.2 on 2025-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_historicallandplot_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'вланість'), ('5', 'аукціон')], max_length=255, null=True, verbose_name='Статус права'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'вланість'), ('5', 'аукціон')], max_length=255, null=True, verbose_name='Статус права'),
        ),
    ]
