# Generated by Django 5.2 on 2025-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_alter_historicallandplot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallandplot',
            name='date_assessment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік розрахунку НГО'),
        ),
    ]
