# Generated by Django 5.2 on 2025-06-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_alter_historicallandplot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandplot',
            name='gidr_constr',
            field=models.CharField(blank=True, choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Гідроспоруда'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='gidr_constr',
            field=models.CharField(blank=True, choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Гідроспоруда'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка'),
        ),
    ]
