# Generated by Django 5.2 on 2025-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_alter_historicallandplot_gidr_constr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallandplot',
            name='has_passport',
            field=models.BooleanField(default=False, verbose_name="Чи є паспорт водного об'єкта?"),
        ),
        migrations.AddField(
            model_name='landplot',
            name='has_passport',
            field=models.BooleanField(default=False, verbose_name="Чи є паспорт водного об'єкта?"),
        ),
    ]
