# Generated by Django 5.2 on 2025-07-01 06:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_auto_20250626_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallandplot',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='landplot',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='has_passport',
            field=models.BooleanField(default=False, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'власність'), ('5', 'аукціон')], max_length=255, null=True, verbose_name='Статус права'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='has_passport',
            field=models.BooleanField(default=False, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'власність'), ('5', 'аукціон')], max_length=255, null=True, verbose_name='Статус права'),
        ),
    ]
