# Generated by Django 5.2 on 2025-07-02 08:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_historicallandplot_geom_landplot_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandplot',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
