# Generated by Django 5.2 on 2025-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0008_alter_historicallandplot_geom_alter_landplot_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallandplot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical land plot', 'verbose_name_plural': 'historical land plots'},
        ),
        migrations.AlterModelOptions(
            name='landplot',
            options={},
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='category',
            field=models.CharField(choices=[('A', '100 Землі сільськогосподарського призначення'), ('B', '200 Землі житлової та громадської забудови'), ('C', '300 Землі природно-заповідного та іншого природоохоронного призначення'), ('D', '400 Землі оздоровчого призначення'), ('E', '500 Землі рекреаційного призначення'), ('F', '600 Землі історико-культурного призначення'), ('G', '700 Землі лісогосподарського призначення'), ('H', '800 Землі водного фонду'), ('I', "900 Землі промисловості, транспорту, зв'язку, енергетики, оборони та іншого призначення")], db_index=True, max_length=10, verbose_name='Категорія землі'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='owner_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='pass_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва паспорту'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'власність'), ('5', 'аукціон')], db_index=True, max_length=255, null=True, verbose_name='Статус права'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='cadastr_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Кадастровий номер'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='category',
            field=models.CharField(choices=[('A', '100 Землі сільськогосподарського призначення'), ('B', '200 Землі житлової та громадської забудови'), ('C', '300 Землі природно-заповідного та іншого природоохоронного призначення'), ('D', '400 Землі оздоровчого призначення'), ('E', '500 Землі рекреаційного призначення'), ('F', '600 Землі історико-культурного призначення'), ('G', '700 Землі лісогосподарського призначення'), ('H', '800 Землі водного фонду'), ('I', "900 Землі промисловості, транспорту, зв'язку, енергетики, оборони та іншого призначення")], db_index=True, max_length=10, verbose_name='Категорія землі'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='owner_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='pass_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва паспорту'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'власність'), ('5', 'аукціон')], db_index=True, max_length=255, null=True, verbose_name='Статус права'),
        ),
        migrations.AddIndex(
            model_name='landplot',
            index=models.Index(fields=['status'], name='land_landpl_status_02716e_idx'),
        ),
        migrations.AddIndex(
            model_name='landplot',
            index=models.Index(fields=['owner_name'], name='land_landpl_owner_n_b3f2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='landplot',
            index=models.Index(fields=['category'], name='land_landpl_categor_013a79_idx'),
        ),
        migrations.AddIndex(
            model_name='landplot',
            index=models.Index(fields=['geom'], name='landplot_geom_idx'),
        ),
    ]
