# Generated by Django 5.2 on 2025-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0009_alter_historicallandplot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallandplot',
            name='sub_owner_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Суборендар'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='sub_rent_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець суборенди'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='sub_rent_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок суборенди'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='suborendar',
            field=models.CharField(blank=True, choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Гідроспоруда'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='sub_owner_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Суборендар'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='sub_rent_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець суборенди'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='sub_rent_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок суборенди'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='suborendar',
            field=models.CharField(blank=True, choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Гідроспоруда'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='owner_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='historicallandplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'власність'), ('5', 'аукціон'), ('6', 'сервітут')], db_index=True, max_length=255, null=True, verbose_name='Статус права'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='owner_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='status',
            field=models.CharField(choices=[('1', 'вільна'), ('2', 'оренда'), ('3', 'постійне користування'), ('4', 'власність'), ('5', 'аукціон'), ('6', 'сервітут')], db_index=True, max_length=255, null=True, verbose_name='Статус права'),
        ),
    ]
