# Generated by Django 5.2 on 2025-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0010_historicallandplot_sub_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandplot',
            name='suborendar',
            field=models.CharField(blank=True, choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Суборенда'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='suborendar',
            field=models.CharField(blank=True, choices=[('1', 'так'), ('2', 'ні')], max_length=10, null=True, verbose_name='Суборенда'),
        ),
    ]
