# Generated by Django 5.2 on 2025-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0011_alter_historicallandplot_suborendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallandplot',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рішення'),
        ),
        migrations.AddField(
            model_name='historicallandplot',
            name='decision_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер рішення'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рішення'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='decision_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер рішення'),
        ),
    ]
