# Generated by Django 5.2 on 2025-05-11 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.png', upload_to='media/user_images', verbose_name='Фото користувача')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Чоловіча'), ('female', 'Жіноча')], max_length=10, verbose_name='Стать')),
                ('subscribe', models.BooleanField(default=False, verbose_name='Підписка на розсилку')),
                ('account_type', models.CharField(choices=[('full', 'Повний пакет'), ('free', 'Безкоштовний пакет')], default='free', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профайл',
                'verbose_name_plural': 'Профайли',
            },
        ),
    ]
